### PR TITLE
docs: add ueberzugpp(1)

### PR DESCRIPTION
**Pull request by Euro20179**
Addresses #28, let me know of any modifications i should make :)

### CODE REVIEW

**Comment by jstkdng** [comment]
Hi thanks for the PR, I added some comments.

**Comment by Euro20179** [comment]
What comments?

**Comment by jstkdng** [comment]
Well, I started a review of the PR

**Comment by Euro20179** [comment]
Shouldn't it show up?

**Review by jstkdng — CHANGES_REQUESTED** [review]

**Comment by jstkdng** [comment]
Lol, forgot to finish the review

**Comment by Euro20179** [comment]
Made some changes.

**Comment by jstkdng** [comment]
alright, lgtm, ty for the contributions. Now I'll have to research how to install this :)

**Comment by Euro20179** [comment]
> Now I'll have to research how to install this :)

i'd put it in the same place you install ueberzugpp to.

For example if you install ueberzugpp to /usr/bin i'd put this in /usr/share/man/man1.

Another example: if ueberzugpp is in /usr/local/bin, i'd put this in /usr/local/share/man/man1

**Pull request merged**
