### PR TITLE
Fix Images opened in an unfocussed Tmux window are overlaid on top of the active window/session

### PR DESCRIPTION
**Pull request by twidxuga**
Addresses [issue  213](https://github.com/jstkdng/ueberzugpp/issues/213), namely: 

- Fix starting `ueberzugpp` in an unfocussed window or session results in image being generated on top of the focussed window and session, instead of hidden in the correct ones, and also in the wrong position.

Additionally:
 
- Removes unused include of the `utilities` library, introduced in [PR #212](https://github.com/jstkdng/ueberzugpp/pull/212)

### CODE REVIEW

**Comment by jstkdng** [comment]
hmmm, i thought it would be a simpler solution but you are touching x11 stuff.

ueberzugpp supports tmux under x11 and wayland so the wayland code should also be changed.

are you sure this is the best way to fix the problem?

**Comment by twidxuga** [comment]
Ahh, of course, it needs to be generic so it works for Wayland too... I was too focussed on X11.

I'll have another look tomorrow and create a new PR if I can crack it, but appreciate any suggestions.

The offending code, that needs to be applicable also for Wayland is just:

From `src/canvas/x11/x11.cpp
```c++
        if (tmux::is_used() && !tmux::is_window_focused()) {
          window->hide();
          return;
        }
```

**Comment by twidxuga** [comment]
From a quick look, I think I can make that code be a method of Canvas, say `init_visibility`, so Canvas needs to be "tmux aware", but not X11 or Wayland. I will still need to change both X11 and Wayland to use that new method, instead of just `show()`, but that seems less of an abstraction break.

More thinking needed.

**Comment by twidxuga** [comment]
Closing this PR. A better solution for controlling initial canvas visibility is needed, one that supports both Wayland and X11. I'll submit another one shortly.

**Comment by twidxuga** [comment]
Closing

**Pull request closed without merging**
