### PR TITLE
docs: add new link of yazi

### PR DESCRIPTION
**Pull request by sxyazi**
Yazi has completed the integration of Überzug++

https://github.com/sxyazi/yazi/pull/12

### CODE REVIEW

**Comment by jstkdng** [comment]
awesome. I see that you implemented your own kitty and iterm2 output, do you get correct output if you sweep through images really fast? My implementation generates garbage when sweeping really fast.

**Comment by sxyazi** [comment]
In my implementation all calculations are async, each rendering task is pausable and discardable, when the previous task is not yet completed and the user issues the next one, the result is simply discarded. That's the same thing about the issue https://github.com/jstkdng/ueberzugpp/issues/99

After all calculations are completed, the result is written using a **locked** stdout pipe, this is critical to make sure that there will not be any contention between the image and the tui rendering threads, otherwise it will make a screen full of escape code.

I tried to use Überzug++'s kitty and iterm2 protocols, but they can't share the same stdout, i.e., there is no way to avoid contention between Überzug++ and the local tui program regarding stdout.

Later I set Überzug++'s stdout to pipe and started a separate thread to listen for new data arrivals (I determine the end of each rendering task by the `\0338` flush from [`restore_cursor_position`](https://github.com/jstkdng/ueberzugpp/blob/a277b04d1b21d9541859e986b90239d2bab7d0c2/src/util/util.cpp#L160C1-L160C1)) and cache them in groups, and only use the last one when actually rendering, but this is too complicated and relies on undefined behavior of upstream.


https://github.com/jstkdng/ueberzugpp/assets/17523360/d8afb891-f439-40cc-a161-d1c2c91aa73f

**Comment by jstkdng** [comment]
I see, but you are using `ueberzugpp`'s sixel and chafa implementation. How are you managing that?

**Comment by sxyazi** [comment]
At the moment I haven't managed to optimize sixel and chafa support because it's difficult with the current architecture -- yep, they still break the screen. I intend to reimplement sixel for yazi soon, and chafa only as a last fallback.

Überzug++ is a great project, and what it really means to me is that it provides support for X11/Wayland environments. I'll explore creating a project similar to Überzug++ later, but as a standalone library that acts as an intermediate layer between the various image protocols, returning the results but not outputting them to stdout, and all tasks will be pausable and discardable.

**Comment by cpbotha** [comment]
> awesome. I see that you implemented your own kitty and iterm2 output, do you get correct output if you sweep through images really fast? My implementation generates garbage when sweeping really fast

I am seeing exactly this with ueberzug 2.9.2 and iterm 3.5.0. With the `lfub` integration, image previewing often works, but unfortunately it often reverts to gibberish on the screen as I move through a sequence of images.

**Comment by jstkdng** [comment]
>I am seeing exactly this with ueberzug

yes, nothing has changed, `u++` and `lf` are fighting for the custody of `stdout`

**Pull request merged**
